### ISSUE TITLE
Multi-Ndless

### ISSUE THREAD

**Issue by lazydogP** [Excale/nLaunchy#12]
Hi! I'm using nLaunchy 2.4 with OS 3.1 & 3.6, and both have their own Ndless resources (ndless_resources.tns for OS 3.1 and ndless_resources_3.6.tns for OS 3.6). Now I want to update nLaunchy for OS 4.2, but I notice it only detects one "ndless_resources.tns". Should I rename those resource files to switch the correct one? Or is there a better solution?

**Comment by Vogtinator** [comment]
ndless_resources.tns from ndless >= 3.9 supports all OSs.

**Comment by lazydogP** [comment]
Yeah, it works fine now. Thanks.
