### ISSUE TITLE
Compiled version fails to load a new operating system

### ISSUE THREAD

**Issue by nahkoots** [Excale/nLaunchy#13]
I'm trying to compile nLaunchy myself. When I do so, the program compiles successfully, and I can install it as an update to an existing nLaunch (by putting the nlaunch.tns file in /nlaunch/). However, if I try to use the nlaunch.tcc file to install it without already having nlaunch present, the loading bar runs to the end, then stops, and refuses to continue (at this point, the debug string is PP123). If I reset the calculator, it stops a little over halfway (debug string PP1234F). The same thing happens if I install it as an update (which does work correctly when rebooting with the same operating system), but then try to change operating systems.
I'm using the unedited source code. The files already available in /nLaunchy-master/CX work. I used an online file checker and found that the files I compiled are almost identical to the ones provided, with a few small differences. I can upload the files I compiled if it will help.

**Comment by nunopenim** [comment]
What is the OS version you are trying to run? I compiled one with "DEBUG 1", and it works fine with OS 3.1, 3.6 and 4.0.2. Haven't tried 4.2 yet

**Comment by Excale** [comment]
> However, if I try to use the nlaunch.tcc file to install it without already having nlaunch present, the loading bar runs to the end, then stops, and refuses to continue (at this point, the debug string is PP123).

'3' means it is installing the OS. I think you need to wait more (it should not take longer than 3 minutes).

**Comment by nahkoots** [comment]
I let it run for 10 minutes with no luck.
When I run "make" for the first time I get an error (see below).
![screenshot from 2016-05-23 18-21-35](https://cloud.githubusercontent.com/assets/19480154/15486436/b8fedf06-2113-11e6-89bc-d8a5c26b19d0.png)

**Comment by Excale** [comment]
Can you upload the compiled version?

**Comment by nahkoots** [comment]
Here it is.
[nLaunchy-master.zip](https://github.com/Excale/nLaunchy/files/294599/nLaunchy-master.zip)

**Comment by Excale** [comment]
I confirm I have an issue with your version.
Where did you get your toolchain?
Which gcc version is it?

**Comment by nahkoots** [comment]
I got my toolchain from the ndless github page. I just followed the tutorial [here](https://github.com/ndless-nspire/Ndless/wiki/Ndless-SDK:-C-and-assembly-development-introduction).

My gcc version is 6.1.0 (at least, there's a folder in /ndless-sdk/ named "gcc-6.1.0, so I assume that's it; if that's not then please tell me how to get the actual version).

**Comment by nahkoots** [comment]
I actually don't know how to fix the toolchain myself. Can you help me with that?

**Comment by Excale** [comment]
Sorry for the delay. I will look at it over the next few days.

**Comment by Excale** [comment]
I made a commit (2124659) which fixes the issue on my side. Is this new version better for you?

**Comment by nahkoots** [comment]
The same error message appears.
I'm sorry, I think I gave you incorrect information. According to apt, my GCC version is 5.3.1. I'm using Ubuntu 16.04. I've read that some people have had issues with GCC 6 on the latest versions of Ubuntu, so that might be the problem. I'll try a lower version of Ubuntu and see if that fixes it.

**Comment by Excale** [comment]
I think gcc 5.3.1 is your host gcc. What is important here is the arm gcc, which Ndless-SDK builds.
Lowering your Ubuntu version should not change anything.

-Update your Ndless SDK
-Update nLaunchy
-Try again

If it still fails, please upload your new nLaunchy-master.zip like you did last time.

**Comment by nahkoots** [comment]
I completely remade the Ndless SDK and used a freshly downloaded copy of nLaunchy (which I confirmed did have your GCC 6 addition) without luck. I got (what appears to be) the same error message.
Below is a screenshot of the command prompt when I compiled the program. I also uploaded my entire Ndless sdk folder to dropbox, in case it would help in any way. nLaunchy-master is in the root of the Ndless folder. I also attached just nLaunchy-master.zip below.
[nLaunchy-master.zip](https://github.com/Excale/nLaunchy/files/345300/nLaunchy-master.zip)
![error_message](https://cloud.githubusercontent.com/assets/19480154/16547575/fdc87afa-4140-11e6-95b3-737a823033a2.png)
https://www.dropbox.com/s/b7e80van1rhkjan/Ndless.zip?dl=0

**Comment by Excale** [comment]
I tried you compiled version. It works fine for me.
This is strange.
Maybe you have some remains of the old version in your CX.
- Backup your Nspire documents
- Go to maintenance menu, delete OS
- Install nLaunchy again (nlaunch.tns + phoenix.tns in nlaunch folder then send nlaunch.tcc)

**Comment by nahkoots** [comment]
I must not have done it right the first time- it works fine now. Thank you for the time you've put in solving this for me.

If it's not too much, can you explain what that line you added does? I can write some code, but how you knew to do that is beyond me.

**Comment by Excale** [comment]
What is does: it tells the compiler that "r9" is used in the assembly snipset.
How I knew to do that: used a debugger to find where it crashed and looked at the assembly code just before that.
