### ISSUE TITLE
Hardware compatibility

### ISSUE THREAD

**Issue by magiricod** [Excale/nLaunchy#15]
Hey I a wondering whether or not nLaunchy still doesn't work onwards from model J hardware down?

**Comment by Excale** [comment]
On CX models, nLaunchy only works with boot2 3.1.0.16.
This boot2 does not work with J+ hardware.
Thus, no nLaunchy for J+ hardware.

**Comment by nunopenim** [comment]
No one still knows why there is this imcompatibility, but it rejects the boot2 code, and (if you don't know how to revert) possibly bricking your device
