### ISSUE TITLE
boot 2 custom logo

### ISSUE THREAD

**Issue by Jakewd** [Excale/nLaunchy#16]
i was looking through the ti-planet archives and found a topic on custom boot2 logos using a modified version of nlaunchy. (https://tiplanet.org/forum/viewtopic.php?t=13857&p=157389) I looked into the Chinese website (http://www.cncalc.org/forum.php?mod=viewthread&tid=9774) that the documantation and files are stored on and downloaded it and voila, after downgrading to its outdated nlaunchy 2.3 it worked! i was wondering if there is anyway to add the code from this modified version to this so that every version from now on has this option. I think its just another cool thing that could be added to make this even better! all the files are on the Chinese website along with the source code. i hope someone looks into this because i wouldn't know how to do it myself haha

**Comment by Excale** [comment]
I do not plan to add this feature to the mainline nLaunchy.
Feel free to make a pull request.
