### ISSUE TITLE
nLaunchy results in "Hanging Clock" on 3.6.0.546

### ISSUE THREAD

**Issue by KazWolfe** [Excale/nLaunchy#4]
When I install 3.6.0.546 CAS on my nSpire CX (revision C), I get the "Hanging Clock". It is patched with TNOC. I have Boot2 version 3.10.16, which really likes nLaunchy.

There is nothing in SRAM, nor does diagnostic mode show anything (even after factory reset). Forcibly removing/replacing the battery does not resolve this problem. As such, this must be a bug with nLaunchy. The OS is (supposedly) supported in the C files, but it is not patching/running successfully.

All other CAS versions work. I have not yet tested 546 as non-CAS (I will do that soon-ish). I have also tried this with and without ndless. It had no effect whatsoever.

**Comment by pacificfils** [comment]
Isn't there some way to trick the OS into seeing the "proper" hardware?

**Comment by Excale** [comment]
There are, but they won't be explained here.
