### ISSUE TITLE
What models does nLaunchy work on?

### ISSUE THREAD

**Issue by Quojil** [Excale/nLaunchy#6]
I have a TI Nspire CX. My hardware revision is T. Will nLaunchy work? I have been googling around for an answer but was unable to find one.

**Comment by Vogtinator** [comment]
It works on boot2 3.1 only. All HW-revisions later than I ("HW-J+") do not support boot2 3.1 and are therefore not capable of running nLaunchy. Yours is T, so sadly way beyond I.

**Comment by Quojil** [comment]
Alright, thank you.
