### ISSUE TITLE
Compile for CX

### ISSUE THREAD

**Issue by deadmeatpt** [Excale/nLaunchy#7]
Hello, I downloaded all the source for nlaunchy. I wanted to compile a version with DEBUG 1, to be stealthy, however, when I do this, with the MODEL as 1, because mine is a CX, I get the following error:

arm-none-eabi-gcc -Os -Wall -Wextra -Werror -Wno-attributes -marm -mcpu=arm926ej-s -s -fPIE -ffreestanding -std=gnu1x -o nlaunch_classic.o -c "-DMODEL=0" nlaunch.c
In file included from nlaunch.c:23:0:
nlaunch.h:29:0: error: "MODEL" redefined [-Werror]
<command-line>:0:0: note: this is the location of the previous definition
cc1.exe: all warnings being treated as errors

make: *** [nlaunch_classic.o] Error 1
Built.

and then, nothing happens. can you please help me?

**Comment by Excale** [comment]
"MODEL" is set directly in the Makefile. The current Makefile builds nLaunchy for *both* Classic and CX (each in a separate directory). Do *not* set "MODEL" in the source code and you will be fine.

**Comment by deadmeatpt** [comment]
Thanks mate!

**Comment by deadmeatpt** [comment]
Another question, is it possible to run OS 4.0 with this? I dont want to upgrade my boot2, because of the possibility to downgrade, and i would enjoy giving 4.0 a try

**Comment by Excale** [comment]
Not yet.
