### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by GuardedAirplane** [Excale/nLaunchy#8]
I am running os 3.6.0.546 which appears to be a supported version, but when I go to install nlaunch, I get the error "The operating system file is corrupt or invalid. Please go to education.ti.com to get a new OS file." Any thoughts would be much appreciated.

**Comment by deadmeatpt** [comment]
Some things: 
1st) In the back of your calc there is a serial code P-XXXX#, where X are numbers and the # is a letter. What is the letter?

2nd) Are you sure you have boot2 3.1 (CX) or 1.4 (Clickpad and Touchpad)?

3rd) The folder inside is to be named nlaunch, not nlaunchy, in case you missed that :)
